### ISSUE TITLE
Feature Request: Move or insert virtual desktop

### ISSUE THREAD

**Issue by LinqLover** [MScholtes/VirtualDesktop#19]
To insert a new virtual desktop between existing virtual desktops, I used to add a new virtual desktop at the end and then move all windows manually by one desktop to the right. However, this is a workaround, and since virtual desktop can be labeled, it gets even more complicated. This tool could be upgraded significantly if it provided an argument to insert a new desktop at a specific position, by moving all windows and labels automatically.

**Comment by MScholtes** [comment]
Hello LinqLover,

that sounds like a lot of coding. Do you have a routine for this already?

Greetings

Markus

**Comment by LinqLover** [comment]
Unfortunately not, but the logic should be simple:

given index i of new desktop:
- append new virtual desktop at the end
- for each window:
   - if its index j >= i:
     - move it to index j + 1

**Comment by MScholtes** [comment]
Hello LinqLover,

sorry for the late answer. I think it could be a bit more complicated: what to do with pinned windows, what about hidden windows, what if a window doesn't like it to be moved (for example has more than one window that have to be on the same desktop)? I will think about it.

Greetings

Markus

**Comment by MScholtes** [comment]
Hello LinqLover,

I released the new version 1.8 of **_VirtualDesktop_** today that has two new parameters _/SwapDesktop_ and _/InsertDesktop_ to rearrange desktops now.
For example you can create a new desktop and put it at the beginning with
```
Virtualdesktop.exe /New /InsertDesktop:0
```

Since in reality not the desktops but the windows are moved there is no guarantee it works for all windows, especially browser windows are dependent from each other and might like not to be moved separately.

Greetings

Markus

**Comment by LinqLover** [comment]
Great, thank you!
