### ISSUE TITLE
Not working on Win11 Insider Preview 22489.1000

### ISSUE THREAD

**Issue by korpa** [MScholtes/VirtualDesktop#31]
Hi,

I was really happy to find this tool, as VDesk was not updated to Win11 yet: https://github.com/eksime/VDesk/issues/92

On my Windows 11 Pro 21H2 (OS build: 22000.258) this runs really great. But sadly on my test machine with Win11 Insider Preview (OS build 22489.1000) it doesn't work. 

I really would like to fix this and create an Pull Request, but as I'm a complete newbie to C# and windows development I have no idea were to start. I understood that MS is changing the API for virtual desk a couple of times in the last windows versions. Therefore I would start there. Could you give me a hint where to start researching about these API changes.

Many thanks

**Comment by MScholtes** [comment]
Hello @korpa,

I'm sorry, but I can't provide support for the _Insider_ versions of _Windows_ because the API can change all the time. The introduction of _Windows 11_ was an exception here, although the _Dev Channel_ was never taken into account here either.

Unfortunately, I can't offer you any programming support either. To work on this project, you need **C#**, **COM** and **deep OS** knowledge.

Greetings

Markus

**Comment by korpa** [comment]
Hi Markus,

sorry that I was not clear. I didn't mean that you should provide programming support for me. I do programming for over 20 years. So to learn C# should not be the problem. My question is where I can find the API documentation for virtual desktops.

**Comment by MScholtes** [comment]
Hello @korpa,

there is no misunderstanding: there is no documentation! 
Microsoft does not support direct addressing of the API for virtual desktops, nor does Microsoft document it, which is perhaps why the API is changed so frequently.

You have to find out everything yourself.

Greetings

Markus

**Comment by korpa** [comment]
Hi Markus,

understood. That's really disappointing. Then I have to decide for my self if I go done the rabbit hole 😆 

Nevertheless, thanks for your work so far on VirtualDesktops. At least I was able to develop a graphical desktop switcher for Win11 based on your work.
![image](https://user-images.githubusercontent.com/2982785/140544439-adf67467-34c8-4301-adea-c6a4ef19b2e5.png)

**Comment by korpa** [comment]
Cool. Will try this. Furthermore I wonder if  #29 will help. Will try this as well.

**Comment by SweetMNM** [comment]
@korpa Hi! Did you get it to work? I am on insider build 22494, and it does not work (which is to be expected).

**Comment by MScholtes** [comment]
Hello @korpa, hello world,

I have no access to _Dev Channel_ versions of _Windows 11 Insider_, so I cannot test any changes for versions 22489 or22494.

If someone could test my suggest change from above ("_...insert the following line IObjectArray GetAllCurrentDesktops();..._") I could build a temporary version with support on success.

Greetings

Markus

**Comment by SweetMNM** [comment]
> 
> 
> Hello @korpa, hello world,
> 
> I have no access to _Dev Channel_ versions of _Windows 11 Insider_, so I cannot test any changes for versions 22489 or22494.
> 
> If someone could test my suggest change from above ("_...insert the following line IObjectArray GetAllCurrentDesktops();..._") I could build a temporary version with support on success.
> 
> Greetings
> 
> Markus

Hi @MScholtes


That worked like magic!
Can't confirm every single functionality of VirtualDesktop works since I haven't tested it all but everything I am interested in (creating, removing desktops. Moving windows etc...) worked perfectly.

Thanks a lot for this awesome project! It's going to be super useful for me :)

Do you want me to create a PR with `VirtualDesktop11Insider.cs`?

**Comment by MScholtes** [comment]
Hello @korpa,

thank you for testing. Since the changes are so few, there is no need for a pull request. I will update an new version in the next minutes.

Greetings

Markus

**Comment by MScholtes** [comment]
New version with **_VirtualDesktop11Insider.cs_** released

**Comment by NyaMisty** [comment]
So why you are turning down my PR?
Microsoft haven't change anything since 22449.

**Comment by MScholtes** [comment]
Hello @NyaMisty,

I only decided to publish another version for the _Dev Channel_ because I saw that the need was greater than expected and when I saw that the difference was only one line. If there are more differences, I will probably remove this version again.

I am very grateful to you for identifying the names, but the pull request is for an older version of _VirtualDesktop_.

I decided to 

Greetings

Markus

**Comment by MScholtes** [comment]
Closed since issue is solved
