### ISSUE TITLE
Is it possible to open an application TO a Virtual Desktop?

### ISSUE THREAD

**Issue by pairofcrocs** [MScholtes/VirtualDesktop#37]
Wondering if my question is out of the scope of this project, but figured I'll ask it anyway.

I'm trying to open up programs on start up to specific virtual desktop.

I know I could set them to auto start via windows and just move them, but preferably, I'd like to do it via the script.

Thanks!

**Comment by MScholtes** [comment]
Hello @pairofcrocs,

as far as I know there is no possibilty to start on a specific virtual desktop, programs always start on the current virtual desktop.

A workaround might be a command line sequence like this (in a batch file):
```cmd
virtualdesktop -GetCurrentDesktop
set DesktopNumber=%ERRORLEVEL%
virtualdesktop -new -switch
start notepad
virtualdesktop -Getdesktop:%DesktopNumber% -Switch
```

Greetings

Markus

**Comment by MScholtes** [comment]
Closed because there is no reaction

**Comment by TH3xACE** [comment]
maintained : https://github.com/LittleVaaty/VDesk
older project: https://github.com/eksime/VDesk

I saw that this project allow to run command on specific desktop with a command like

+ Run notepad on virtual desktop number 4 without switching:
vdesk run -n -o 4 notepad.exe

If it can help some people... @MScholtes  is it something that can be implemented in your project ? I like your project since it is easier to understand the code flow and what it is doing.
