### ISSUE TITLE
A Question: Which file will be used for which build range ?

### ISSUE THREAD

**Issue by Taster-git** [MScholtes/VirtualDesktop#64]
Hi,
Which file will be used for which build range as we have 
Single [VirtualDesktop](https://github.com/MScholtes/VirtualDesktop/blob/master/VirtualDesktop.cs), surly which will be used for all windows 10 build range from 19041 to less than 22000.
But what are ranges for these 3 files for Window 11 ?
[VirtualDesktop11-21H2](https://github.com/MScholtes/VirtualDesktop/blob/master/VirtualDesktop11-21H2.cs)
[VirtualDesktop11.cs](https://github.com/MScholtes/VirtualDesktop/blob/master/VirtualDesktop11.cs)
[VirtualDesktopInsider.cs](https://github.com/MScholtes/VirtualDesktop/blob/master/VirtualDesktopInsider.cs)

I am confused. Please guide @MScholtes @NyaMisty or anyone

**Comment by MScholtes** [comment]
Hello @Taster-git,

it's not that complicated:
**VirtualDesktop11.cs** is for the current version of **Windows 11**, that means **Windows 11 22H2**.
**VirtualDesktop11-21H2.cs** is for **Windows 11 21H2**.
**VirtualDesktopInsider.cs** is for **Insider** versions of **Windows 11**, but seems not to work anymore.

Greetings

Markus

**Comment by MScholtes** [comment]
Hello @Taster-git,

there are two versions of .Net:
The .Net Framework, which is integrated in every Windows and supports platform-specific functions.
Then the .Net Core, which works across operating systems and therefore does not offer platform support.

The Windows virtual desktops are platform-specific, so they can only be addressed by the .Net Framework. For the reasons given above, I will certainly not change this.

However, there are implementations that provide special declarations or libraries so that .Net Core also works.

Please understand that I cannot help, it is not my mission to help programming novices, I often find it hard to maintain my own projects as I do all of this in my spare time. Can you try to target .Net Framework in your VS project?

Greetings

Markus

**Comment by MScholtes** [comment]
Answered
