### ISSUE TITLE
Problem moving active window to desktop

### ISSUE THREAD

**Issue by norrin77** [MScholtes/VirtualDesktop#72]
Hi and thanks for your awesome work.

I cannot get the /MOVEACTIVEWINDOW to do the task. I don't know if it's my command or if it's a new issue. So far I've tried with:

VirtualDesktop11.exe Q "Desktop 2" /MOVEACTIVEWINDOW /SWITCH
VirtualDesktop11.exe /MOVEACTIVEWINDOW:"Desktop 2" /SWITCH
VirtualDesktop11.exe /MOVEACTIVEWINDOW /SWITCH:"Desktop 2"

I've also tried replacing the desktop id with a number (just "2"). None of them seem to move the active window to the requested desktop.

I've also tried your example:

> VirtualDesktop11.exe Q N /MOVEACTIVEWINDOW /SWITCH

 to move active window to a new desktop, but only new desktop is created and active window remains on source desktop.

I'm on Windows 11. 

Could it be a bug?

Thanks again.

**Comment by MScholtes** [comment]
Hello @norrin77,

your 3 tries have failures in the parameters. You first have to select the desktop you want to move the window to:
_VirtualDesktop11.exe Q "/GETDESKTOP:Desktop 2" /MOVEACTIVEWINDOW /SWITCH_
should work (and it does work for me).

_VirtualDesktop11.exe Q N /MOVEACTIVEWINDOW /SWITCH_
works for me too (with N the new desktop is selected).

A problem that can occur that the active window does not want to be moved or cannot be moved, maybe because there are several windows of the program. For example it is not easy to move **Edge** or **Firefox**, you have to move the correct window there which does not has to be the active.

To examine this maybe you try it with a **Notepad** window first?

Greetings

Markus

**Comment by norrin77** [comment]
Hi again MScholtes, thanks for your kind feedback.

The first command you wrorte did the trick: VirtualDesktop11.exe Q "/GETDESKTOP:Desktop 2" /MOVEACTIVEWINDOW /SWITCH

So no issue here.

Thanks again and kind regards.
